<?php
// $Id$

/**
 * Implement hook_permission().
 */
function qunit_permission() {
  if (!module_exists('simpletest')) {
    return array(
      'administer unit tests' => array(
        'title' => t('Administer unit tests'),
        'description' => t('Manage and run automated testing. %warning', array('%warning' => t('Warning: Give to trusted roles only; this permission has security implications.'))),
      ),
    );
  }
}


/**
 * Implement hook_menu().
 */
function qunit_menu() {
  $items = array();

  $items['admin/config/development/qunit'] = array(
    'title' => 'JavaScript testing',
    'description' => "Run the tests for Drupal's JavaScript code, which will make sure that the JavaScript works properly your browser.",
    'page callback' => 'qunit_run_tests',
    'access arguments' => array('administer unit tests'),
  );

  return $items;
}

/**
 * Implement hook_library().
 */
function qunit_library() {
  $libraries = array();

  $libraries['qunit'] = array(
    'title' => 'QUnit',
    'website' => 'http://docs.jquery.com/QUnit',
    'version' => 'dev',
    'js' => array(
      drupal_get_path('module', 'qunit') . '/testrunner.js' => array('weight' => -6),
      drupal_get_path('module', 'qunit') . '/test.js' => array('weight' => -5),
    ),
    'css' => array(
      drupal_get_path('module', 'qunit') . '/testsuite.css' => array(),
    ),
  );

  return $libraries;
}

/**
 * Page callback to run the tests.
 */
function qunit_run_tests() {
  drupal_add_library('qunit', 'qunit');
  foreach (module_list() as $module) {
    $directory = drupal_get_path('module', $module);
    if (file_exists("$directory/$module.test.js") && is_file("$directory/$module.test.js")) {
      drupal_add_js("$directory/$module.test.js");
    }
    if (file_exists("$directory/tests") && is_dir("$directory/tests")) {
      foreach (file_scan_directory("$directory/tests", '/.*?\.test\.js/') as $file) {
        drupal_add_js($file->uri);
      }
    }
  }
  print '<html><head><title>' . drupal_get_title() . '</title>' . drupal_get_js() . drupal_get_css() . '</head><body id="body">
        <h1 id="header">Drupal JavaScript Test Suite</h1>
        <h2 id="banner"></h2>
        <h2 id="userAgent"></h2>
        <ol id="tests"></ol>
        <div id="main" style="display: none;"></div>
</body></html>';
}
